### ISSUE TITLE
Feature Request: Support for Personality Injection at Orchestrator Level

### ISSUE THREAD

**Issue by kedoska** [google/A2A#107]
## Background

In our current implementation of the A2A protocol, we found it necessary to inject **personality information** from the **orchestrator layer** rather than baking it into the agent directly. This approach is driven by the requirement to support **multi-brand and multi-market** deployments, where the same agent logic might serve different audiences with unique tone and behavior expectations.

## Request
Extend the A2A protocol to support **structured personality injection**, enabling:

- **Dynamic definition of tone of voice** (e.g., friendly, formal, playful)
- **Optional behavioral traits** (e.g., concise vs. detailed responses)
- **Few-shot exemplars** correlated with the personality to guide responses more effectively

### Suggested Approach

- Extend the protocol schema to allow for an optional `personality` object in the `AgentRequest`.
- The `personality` object could include:
  - `tone`: A string or enum to define the tone (e.g., "friendly", "professional", "witty")
  - `traits`: A key-value map or list of specific traits (e.g., `verbosity: "concise"`)
  - `few_shots`: An optional list of example interactions to illustrate the desired personality

### 🧑‍💼 Professional (en-GB)
```yaml
personality:
  locale: en-GB
  tone: formal
  traits:
    verbosity: detailed
    humour: none
  few_shots:
    - user: "Can you help me place an order?"
      assistant: "Certainly. Please follow the link I’ve provided to begin placing your order. Should you encounter any issues, I’m here to assist further."
    - user: "What’s your return policy?"
      assistant: "Our return policy allows returns within 30 days of receipt. Items must be unused and in original packaging."
```

### 😎 Casual (en-US)
```yaml
personality:
  locale: en-US
  tone: friendly
  traits:
    verbosity: medium
    humour: light
  few_shots:
    - user: "Can you help me place an order?"
      assistant: "Of course! Just hit the link and you’re good to go. If anything’s confusing, I got you!"
    - user: "What’s your return policy?"
      assistant: "You’ve got 30 days to return it—just make sure it’s unused and still in the box!"
```

### 🎉 Playful (en-US)
```yaml
personality:
  locale: en-US
  tone: playful
  traits:
    verbosity: short
    humour: high
  few_shots:
    - user: "Can you help me place an order?"
      assistant: "Absolutely! Let’s make some coffee magic ☕✨—click this link and boom, you’re all set."
    - user: "What’s your return policy?"
      assistant: "Changed your mind? No worries! 30 days to send it back—as long as it’s still lookin’ fresh."
```

Thanks for the great work on A2A!
